#!/bin/bash
# End-to-end tests for flowcode: compiler → bytecode → runtime
# Exit on first failure
set -euo pipefail

PASS=0
FAIL=0
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
FLOWCODE="$ROOT_DIR/flowcode"
COMPILER="$ROOT_DIR/dist/compiler/index.js"
TMP_DIR="$(mktemp -d)"

cleanup() {
    rm -rf "$TMP_DIR"
}
trap cleanup EXIT

pass() {
    PASS=$((PASS + 1))
    printf "  PASS: %s\n" "$1"
}

fail() {
    FAIL=$((FAIL + 1))
    printf "  FAIL: %s\n" "$1"
}

assert_exit() {
    local expected="$1"
    local actual="$2"
    local desc="$3"
    if [ "$actual" -eq "$expected" ]; then
        pass "$desc"
    else
        fail "$desc (expected exit $expected, got $actual)"
    fi
}

# Helper: write a raw .fcb file from hex-like binary data via C helper
write_fcb() {
    local path="$1"
    shift
    # Use printf to write binary data
    printf '%b' "$@" > "$path"
}

# Helper: compile a .fc file with the TypeScript compiler
compile_fc() {
    local input="$1"
    local output="$2"
    node "$COMPILER" "$input" "$output"
}

printf "=== Flowcode E2E Tests ===\n\n"

# ---------- Section 1: CLI error handling ----------
printf "%s\n" "-- CLI error handling --"

# Test: no arguments
set +e
"$FLOWCODE" > /dev/null 2>&1
assert_exit 1 $? "CLI exits 1 with no arguments"

# Test: missing 'run' subcommand
"$FLOWCODE" exec foo.fcb > /dev/null 2>&1
assert_exit 1 $? "CLI exits 1 with unknown subcommand"

# Test: missing file
"$FLOWCODE" run "$TMP_DIR/nonexistent.fcb" > /dev/null 2>&1
assert_exit 1 $? "CLI exits 1 with missing file"

# Test: invalid (non-FCB) file
echo "this is not a valid bytecode file" > "$TMP_DIR/invalid.fcb"
"$FLOWCODE" run "$TMP_DIR/invalid.fcb" > /dev/null 2>&1
assert_exit 1 $? "CLI exits 1 with invalid bytecode file"

# Test: empty file
: > "$TMP_DIR/empty.fcb"
"$FLOWCODE" run "$TMP_DIR/empty.fcb" > /dev/null 2>&1
assert_exit 1 $? "CLI exits 1 with empty file"

# Test: truncated header (only magic bytes)
printf 'FCB1' > "$TMP_DIR/truncated.fcb"
"$FLOWCODE" run "$TMP_DIR/truncated.fcb" > /dev/null 2>&1
assert_exit 1 $? "CLI exits 1 with truncated header"
set -e

printf "\n"

# ---------- Section 2: Bytecode programs built in C test helpers ----------
printf "%s\n" "-- VM execution via CLI (C-generated bytecode) --"

# Build and run the C e2e helpers
"$ROOT_DIR/tests/test_e2e_emit_store" > /dev/null 2>&1
assert_exit 0 $? "emit+store program runs successfully"

"$ROOT_DIR/tests/test_e2e_transform" > /dev/null 2>&1
assert_exit 0 $? "transform-only program runs successfully"

"$ROOT_DIR/tests/test_e2e_route" > /dev/null 2>&1
assert_exit 0 $? "route program runs successfully"

set +e
"$ROOT_DIR/tests/test_e2e_invalid_opcode" > /dev/null 2>&1
assert_exit 0 $? "invalid opcode test detects bad opcode"
set -e

printf "\n"

# ---------- Section 3: Compiler → Runtime pipeline ----------
printf "%s\n" "-- Compiler to runtime pipeline --"

# Test: compile and run a simple emit-only flow
cat > "$TMP_DIR/emit_only.fc" <<'EOF'
workflow: EmitOnly

step done:
    emit
        value = "complete"
end

end
EOF

compile_fc "$TMP_DIR/emit_only.fc" "$TMP_DIR/emit_only.fcb"
"$FLOWCODE" run "$TMP_DIR/emit_only.fcb"
assert_exit 0 $? "compile and run emit-only flow"

# Test: compile and run a flow with emit + store
cat > "$TMP_DIR/emit_store.fc" <<'EOF'
workflow: EmitStore

step data:
    emit
        value = "hello"
end

step saved:
    store set
        key = "test"
        value = data
end

end
EOF

compile_fc "$TMP_DIR/emit_store.fc" "$TMP_DIR/emit_store.fcb"
"$FLOWCODE" run "$TMP_DIR/emit_store.fcb"
assert_exit 0 $? "compile and run emit+store flow"

# Test: compile and run a flow with transform
cat > "$TMP_DIR/transform.fc" <<'EOF'
workflow: TransformFlow

step normalized:
    transform normalize.input
        input = payload
end

step done:
    emit
        value = "complete"
end

end
EOF

compile_fc "$TMP_DIR/transform.fc" "$TMP_DIR/transform.fcb"
"$FLOWCODE" run "$TMP_DIR/transform.fcb"
assert_exit 0 $? "compile and run transform+emit flow"

# Test: compile and run a flow with route (match)
cat > "$TMP_DIR/route.fc" <<'EOF'
workflow: RouteFlow

step data:
    emit
        value = "hello"
end

match data.status
    approved ->
        step ok:
            emit
                value = "approved"
        end
end

step saved:
    store set
        key = "result"
        value = data
end

end
EOF

compile_fc "$TMP_DIR/route.fc" "$TMP_DIR/route.fcb"
"$FLOWCODE" run "$TMP_DIR/route.fcb"
assert_exit 0 $? "compile and run route+emit+store flow"

# Test: compile a complex multi-step flow (no call/plugins, so runtime can execute)
cat > "$TMP_DIR/multi_step.fc" <<'EOF'
workflow: MultiStep

step a:
    emit
        value = "step_a"
end

step b:
    transform merge
        input = a
end

step c:
    store set
        key = "result"
        value = b
end

step d:
    emit
        value = "done"
end

end
EOF

compile_fc "$TMP_DIR/multi_step.fc" "$TMP_DIR/multi_step.fcb"
"$FLOWCODE" run "$TMP_DIR/multi_step.fcb"
assert_exit 0 $? "compile and run multi-step flow"

printf "\n"

# ---------- Section 4: Compiler error handling ----------
printf "%s\n" "-- Compiler error handling --"

set +e
# Test: compiler with missing arguments
node "$COMPILER" > /dev/null 2>&1
assert_exit 1 $? "compiler exits 1 with no arguments"

# Test: compiler with only input arg
node "$COMPILER" "$TMP_DIR/emit_only.fc" > /dev/null 2>&1
assert_exit 1 $? "compiler exits 1 with missing output argument"
set -e

# Test: compiler with non-existent input file
set +e
node "$COMPILER" "$TMP_DIR/nonexistent.fc" "$TMP_DIR/out.fcb" > /dev/null 2>&1
assert_exit 1 $? "compiler exits 1 with non-existent input file"
set -e

# Test: compiler produces valid header
compile_fc "$TMP_DIR/emit_only.fc" "$TMP_DIR/header_check.fcb"
MAGIC=$(head -c 4 "$TMP_DIR/header_check.fcb")
if [ "$MAGIC" = "FCB1" ]; then
    pass "compiled file has correct FCB1 magic header"
else
    fail "compiled file has wrong magic header: $MAGIC"
fi

printf "\n"

# ---------- Section 5: Compiler semantic validation ----------
printf "%s\n" "-- Compiler semantic validation --"

# Test: duplicate step names produce an error diagnostic
cat > "$TMP_DIR/dup_steps.fc" <<'EOF'
workflow: DupSteps

step alpha:
    emit
        value = "one"
end

step alpha:
    emit
        value = "two"
end

end
EOF

set +e
DIAG=$(compile_fc "$TMP_DIR/dup_steps.fc" "$TMP_DIR/dup_steps.fcb" 2>&1)
RC=$?
set -e
if echo "$DIAG" | grep -qi "duplicate step"; then
    pass "compiler detects duplicate step names"
else
    fail "compiler should detect duplicate step names"
fi

# Test: on_error, retry, timeout, compensate are recognized (no unrecognized warnings)
cat > "$TMP_DIR/error_constructs.fc" <<'EOF'
workflow: ErrorHandling

step data:
    emit
        value = "payload"
end

step action:
    http.get
    on_error retry
end

end
EOF

set +e
DIAG=$(compile_fc "$TMP_DIR/error_constructs.fc" "$TMP_DIR/error_constructs.fcb" 2>&1)
set -e
if echo "$DIAG" | grep -qi "unrecognized.*on_error\|unrecognized.*retry\|unrecognized.*timeout\|unrecognized.*compensate"; then
    fail "compiler should recognize error-handling constructs"
else
    pass "compiler recognizes on_error/retry/timeout/compensate constructs"
fi

printf "\n"

# ---------- Summary ----------
TOTAL=$((PASS + FAIL))
printf "=== Results: %d/%d passed ===\n" "$PASS" "$TOTAL"
if [ "$FAIL" -gt 0 ]; then
    exit 1
fi
exit 0
